

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone : http://${eureka.instance.hostname}:8761/eureka/

  server:
    eviction-interval-timer-in-ms: 5000

spring:
  application:
    name: gateway-routing
  cloud:
    gateway:
      routes:
#        - id: order-service
#          predicates:
#            - Path=/api/orders/**
#          uri: https://nexio-orders-api.herokuapp.com/
  
#              
#        - id: stocks-service
#          predicates:
#            - Path=/api/stocks/**
#          uri: https://nexio-stocks-api.herokuapp.com/
#

          
        - id: order-service
          predicates:
            - Path=/api/orders/**
          uri: http://localhost:9090/
       
                    
        - id: stock-service
          predicates:
            - Path=/api/stocks/**
          uri: http://localhost:9191/  
                
        
            
            